from bluesky import RunEngine
from scripts.plans import grid_scan, just_traj_scan, traj_panda_scan  # noqa: F401

RE = RunEngine()
# RE(just_traj_scan())
RE(traj_panda_scan())
# RE(grid_scan())


# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# print("\n\n\n-------------------------10-----------------------------\n\n\n")

# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# print("\n\n\n-------------------------20-----------------------------\n\n\n")

# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# print("\n\n\n-------------------------30-----------------------------\n\n\n")

# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# print("\n\n\n-------------------------40-----------------------------\n\n\n")

# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# RE(traj_panda_scan())
# print("\n\n\n-------------------------50-----------------------------\n\n\n")
